apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    name: goserver
spec:
  selector:
    matchLabels: 
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: lccoornel/hello-go:v5.3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1

        envFrom:
          - configMapRef:
              name: goserver-env
          - secretRef:
              name: goserver-secret
        
        volumeMounts:
          - mountPath: "/go/myfamily"
            name: config
        # env:
        #   - name: NAME
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: NAME
              
        #   - name: AGE
        #     valueFrom:
        #       configMapKeyRef:
        #         name: goserver-env
        #         key: AGE
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items: 
            - key: members
              path: "family.txt"
    